# Generated by Django 4.1.7 on 2023-03-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=150, null=True)),
                ('complated', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
